[package]
name = "lyre"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive", "wrap_help"] }
midly = "0.5.3"
pest = "2.7.7"
pest_derive = "2.7.7"
